### PR TITLE
Update directory-watcher to 0.18.0

### PR DESCRIPTION
**Pull request by wborn**
Updates the directory-watcher from 0.17.1 to 0.18.0.

This version has some bug fixes/improvements, see:

https://github.com/gmethvin/directory-watcher/compare/v0.17.1...v0.18.0

### CODE REVIEW

**Comment by jlaur** [comment]
@wborn - do you think this could be related to some of the issues reported on the forum with .things/.sitemap files not loading correctly? For example:
- https://community.openhab.org/t/changes-in-thing-config-files-not-populated-in-oh4/149208
- https://community.openhab.org/t/bug-since-oh4-why-are-the-default-sitemap-and-things-files-not-loaded-on-startup-empty-sitemap-list/148198

**Comment by wborn** [comment]
Yes I also read those posts so I thought it might help to update this library.

**Comment by wborn** [comment]
This fix may also help: https://github.com/openhab/openhab-core/pull/3779

**Comment by jlaur** [comment]
@wborn, @J-N-K - yes, I also saw this one in relation to:
- https://community.openhab.org/t/4-0-1-cannot-delete-or-modify-things-that-are-provisioned-from-file/148518

Next question for both of you: How would you assess the risk for these PR's? I'm wondering if they should be candidates for 4.0.x backporting? I have no clue how many users are affected - for some reason my setup (Raspberry Pi 3, openHABian 1.8, openHAB 4.0.2 using file-based configuration) doesn't seem affected so far. But it does seem to come up somewhat repeatedly in the forum without any good fixes or work-arounds.

**Comment by wborn** [comment]
> How would you assess the risk for these PR's? I'm wondering if they should be candidates for 4.0.x backporting?

Let's give them a test in the snapshots. Then we can backport them if nothing comes up or it is reported to work better.

**Comment by J-N-K** [comment]
The other issue (cannot load modification) only occurs if you have things from different bindings in the same .things file, so it depends on how you organize your things if you are affected or not.

**Comment by jlaur** [comment]
> The other issue (cannot load modification) only occurs if you have things from different bindings in the same .things file, so it depends on how you organize your things if you are affected or not.

Yes, this is probably relatively rare, and there is a good work-around.

**Comment by lolodomo** [comment]
> The other issue (cannot load modification) only occurs if you have things from different bindings in the same .things file,

Ah ok., I have always one file per binding in my case. 
Is it an issue introduced in OH4 or is it like that since the first day if OH?

**Comment by J-N-K** [comment]
Not sure. It could be a side-effect of the fix for "config changes not considered when reloading a .things file".

**Comment by andrewfg** [comment]
> this is probably relatively rare

Maybe it is rare. But it is my case, so I am strongly interested in a fix.

> and there is a good work-around.

Not in my case. I have an automated Excel database where I keep track of all things and items, and which generates one .things file, .items file, and .sitemap file containing everything.

And anyway, I don't think having an ostensible work around is any reason for not fixing what is patently a bug.

**Comment by andrewfg** [comment]
> Is it an issue introduced in OH4 or is it like that since the first day if OH?

It is new in OH 4.0.x

**Comment by andrewfg** [comment]
BTW I think the issue with "config changes not propagating" might not be fixed by the directory watcher update. Reason is that after editing a .things file, the log does contain a "Loading things" entry, so it clearly detects the file change.

But the new data within those things  is not updated, so perhaps the issue is due to the comparison of the timestamp on the changed .things file versus the timestamp on the cached data within OH. => I wonder if the file system and the OH core are comparing different date time instants in different time zones?? I guess you guys are mostly on CET whereas I for example am on BST..

**Comment by wborn** [comment]
Try the snapshots to see if your issue is fixed by openhab/openhab-core#3779.

**Pull request merged**
