### PR TITLE
Changed location of files from Bintray to Artifactory and removed unused libs

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by wborn** [comment]
Shouldn't we also update the openhab-super-pom version? Did you also add all manually added JAR files to Artifact pry?

**Comment by wborn** [comment]
We can probably also remove net.wimpi.jamod since it is embedded in the modbus-transport in openhab-core.

**Comment by kaikreuzer** [comment]
Looks as if we should upgrade lazysodium, which is now on Maven Central under a different group Id: https://github.com/terl/lazysodium-java/releases

**Comment by kaikreuzer** [comment]
Nah, it can actually be removed as it isn't used either anymore...

**Comment by wborn** [comment]
I did a local build and these still fail for me:

```
de.kaizencode.tchaikovsky
io.moquette.moquette-broker
org.java-websocket.java-websocket
```

**Comment by kaikreuzer** [comment]
We are not using moquette anymore and I cannot find any references to java-websocket, so I guess we can remove them as well.

**Comment by kaikreuzer** [comment]
I'm only getting a `bnd error: null: ConcurrentModificationException` locally, that's why I couldn't test...

**Review by wborn — APPROVED** [review]
Great, it works now. :slightly_smiling_face:  Thanks for your help! :+1:

**Comment by kaikreuzer** [comment]
Finally green!

**Pull request merged**
