### PR TITLE
Add hubspot immutables-exceptions

### PR DESCRIPTION
**Pull request by ccutrer**
A new dependency of jinjava

### CODE REVIEW

**Comment by jimtng** [comment]
@wborn / @J-N-K at the moment the issue with mqtt.homeassistant is causing some problems with the snapshot build. Hopefully this + the corresponding addon PR would fix it. Once merged, the build needs to be triggered for openhab-osgiify

**Comment by ccutrer** [comment]
Ping @lsiepel

**Comment by lsiepel** [comment]
I would expect this to also be added to the root pom.xml as module

**Comment by ccutrer** [comment]
> I would expect this to also be added to the root pom.xml as module

🤦 good call. done

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM!
@wborn or @J-N-K can you start the build to publish the artifacts?

**Comment by J-N-K** [comment]
Done

**Comment by ccutrer** [comment]
https://ci.openhab.org/view/Release%20Jobs/job/openhab-osgiify/40/console failed (with the encoding thing), and needs run again

**Pull request merged**
